# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 60

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: -1 # Close the issue almost immediately. See: https://github.com/probot/stale/issues/131

# Issues with these labels will never be considered stale
exemptLabels:
  - blocker
  - security
  
# Label to use when marking an issue as stale
staleLabel: "[Status] Stale"

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. Please check if this issue is still relevant and please close it if it's not.
  This will make sure that our open issues are actually of use and reduce the list of obsolete issues.
  Thank you for your contributions.
  
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
