matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libx11-dev
            - libxext-dev
            - libxss-dev
            - libxkbfile-dev
            - rpm
    - os: osx
      if: branch = release
      osx_image: xcode11

language: node_js
git:
  submodules: false
branches:
  only:
    - develop
    - release
    - nightly
cache: npm

before_install:
  - git submodule update --init --recursive
install:
  - travis_retry npx lerna bootstrap
  - travis_retry npm install node-sass -g
before_script:
  - npm run lint && npm run test
script:
  - |
    if [ $TRAVIS_BRANCH == "release" ]; then
      travis_retry travis_wait 100 npm run build
    fi
  - |
    if [ $TRAVIS_BRANCH == "nightly" ]; then
      travis_retry travis_wait 100 npm run build -- --publish always -c.publish.repo=ferdi-nightly
    fi

