matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libx11-dev
            - libxext-dev
            - libxss-dev
            - libxkbfile-dev
            - rpm
    - os: osx
      osx_image: xcode11

language: node_js
# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - git submodule update --init --recursive
install:
  - echo do nothing
before_script:
  - travis_retry npx lerna bootstrap
  - travis_retry npm install node-sass -g
script:
  - travis_retry travis_wait 100 npm run build
cache: npm

branches:
  except:
    - i18n
    - l10n_master
    - l10n_develop
