matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libx11-dev
            - libxext-dev
            - libxss-dev
            - libxkbfile-dev
            - rpm
    - os: osx
      if: branch IN (nightly, release)
      osx_image: xcode11

language: node_js
git:
  submodules: false
branches:
  only:
    - develop
    - release
    - nightly
cache: npm

before_install:
  - git submodule update --init --recursive
  - |
    if [ $TRAVIS_BRANCH == "nightly" ]; then
      git remote add source https://${GH_TOKEN}@github.com/getferdi/ferdi.git > /dev/null 2>&1
      git fetch source
      git merge --no-ff --commit --no-edit source/develop
      changes=$(git diff --stat HEAD origin/nightly | wc -l)
      if [ $changes -eq 0 ]; then
        travis_terminate 0;
      else
        git submodule update --remote --force
        git add .
        git commit -m "Update submodules"
      fi
    fi
install:
  - cd recipes && npm install && npm run package && cd ..
  - travis_retry npx lerna bootstrap
  - travis_retry npm install node-sass -g
before_script:
  - npm run lint && npm run test
script:
  - |
    if [ $TRAVIS_BRANCH == "release" ]; then
      travis_retry travis_wait 100 npm run build 
    fi
  - |
    if [ $TRAVIS_BRANCH == "nightly" ]; then
      npm version prerelease --preid=nightly -m "%s and trigger AppVeyor nightly build [skip travisci]"
      travis_retry travis_wait 100 npm run build -- --publish always -c.publish.provider=github -c.publish.owner=getferdi -c.publish.repo=nightlies
      if [ $TRAVIS_OS_NAME == "osx" ]; then
        git remote add nightly https://${GH_TOKEN}@github.com/getferdi/ferdi.git > /dev/null 2>&1
        git push --quiet --set-upstream nightly HEAD:nightly >/dev/null 2>&1
      fi
    fi
