matrix:
  include:
  - os: linux
    dist: xenial
    addons:
      apt:
        packages:
        - libx11-dev
        - libxext-dev
        - libxss-dev
        - libxkbfile-dev
  - os: osx
    osx_image: xcode11

language: node_js
install:
  - echo do nothing
before_script:
  - npx lerna bootstrap
  - npm install node-sass -g
script:
  - npm run test
  - travis_wait 30 npm run build
cache: npm

branches:
  except:
    - i18n
    - l10n_master
