matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libx11-dev
            - libxext-dev
            - libxss-dev
            - libxkbfile-dev
            - rpm
    - os: osx
      osx_image: xcode11

language: node_js
git:
  submodules: false
branches:
  only:
    - develop
    - release
cache: npm

before_install:
  - git submodule update --init --recursive
install:
  - travis_retry npx lerna bootstrap
  - travis_retry npm install node-sass -g
before_script:
  - npm run lint && npm run test
script:
  - echo $TRAVIS_BRANCH

