version: build-{build}
branches:
  only:
    - release
    - nightly
skip_tags: true
skip_branch_with_pr: true

cache:
  - '%APPDATA%\npm-cache'
  - node_modules

install:
  - appveyor-retry git submodule update --init --recursive
  - ps: Install-Product node 10
  - appveyor-retry npx lerna bootstrap

before_build:
  - npm run lint && npm test
  - cmd: set NODE_ENV=production

build_script:
  - appveyor-retry npm run build

-
  branches:
    only:
      - nightly
  before_build:
    - npm version prerelease --preid=nightly
