environment:
  APPVEYOR_CACHE_SKIP_RESTORE: true

version: 5.4.1-beta.4.{build}

install:
  - appveyor-retry git submodule update --init --recursive
  - ps: Install-Product node 10
  - appveyor-retry npx lerna bootstrap

cache:
  - '%APPDATA%\npm-cache'

before_build:
  - npm run lint
  - cmd: set NODE_ENV=production

build_script:
  - appveyor-retry npm run build

branches:
  except:
    - i18n
    - l10n_master
    - l10n_develop

skip_commits:
  files:
    - src/i18n/locales/*.json
