environment:
  APPVEYOR_CACHE_SKIP_RESTORE: true

version: 5.0.1.{build}

install:
  - ps: $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
  - ps: $fileContent += $env:priv_key.Replace(' ', "`n")
  - ps: $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
  - ps: Set-Content $env:userprofile\.ssh\id_rsa $fileContent
  - git submodule update --init --recursive
  - ps: Install-Product node 10
  - npx lerna bootstrap

cache:
  - '%APPDATA%\npm-cache'

before_build:
  - npm run lint
  - npm run test

build_script:
  - npm run build

on_success:
  - ps: Get-ChildItem .\out\*.exe | % { Push-AppveyorArtifact $_.FullName }

branches:
  except:
    - i18n
    - l10n_master
    - l10n_develop

for:
  - branches:
      only:
        - master
        - /v\d*\.\d*\.\d*/
        - /v\d*\.\d*\.\d*-beta\.\d*/
    artifacts:
      - path: out\*.exe
      - path: out\*.yml
