# This workflow will do a clean install of ferdi dev-dependencies, update the dependencies, build the source code and run tests. It will only run on scheduled trigger.

name: Ferdi Dependency updates

on:
  # Manual trigger from the UI
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for build'
        required: true
  schedule:
    - cron: '0 0 * * *' # every night at 12 am

env:
  USE_HARD_LINKS: false

jobs:
  dependency_updates:
    runs-on: ubuntu-latest
    steps:
      - name: Set env vars
        run: |
          echo "NPM_CACHE=$HOME/.npm" >> $GITHUB_ENV
      - name: Checkout code along with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.NPM_CACHE }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js 14.16.1
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.1
      - name: Uninstall locally and reinstall node-gyp globally
        run: |
          npm uninstall node-gyp
          npm i -g node-gyp@8.0.0 && npm config set node_gyp "$(which node-gyp)"
      - name: Install node dependencies recursively
        run: npx lerna bootstrap
      - name: Update submodules, dependencies and run tests
        run: |
          echo "Updating submodules"
          git submodule update --remote -f

          echo "Updating browserslist db"
          npx browserslist@latest --update-db

          echo "Running linter, reformatter, rebrander and tests"
          npm run lint
          npm run reformat-files
          npm run manage-translations
          npm run apply-branding
          npm run test

          echo "Committing submodules, dependency-updates and linter changes"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Update submodules, browserslist data updates and linter fixes [skip ci]" --no-verify || true

          echo "Bumping version number"
          GIT_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          CHANGES_COUNT=$(git diff --shortstat origin/$GIT_BRANCH_NAME | wc -l)
          MANUAL_REBUILD="${{ github.event_name == 'workflow_dispatch' }}"
          # if this is a scheduled build or has been manually triggered with 'version bump' in the text, then bump the version number
          if [ $MANUAL_REBUILD != "true" ] || [ "${{ contains(github.event.inputs.message, 'version bump') }}" == "true" ]; then
            echo "Bumping version number"
            npm version prerelease --preid=nightly
          fi

          echo "Pushing all changes"
          git push origin $GIT_BRANCH_NAME --no-verify
